### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by luisfelipesdn12** [Nalanda-Dias/Calculadora#1]
Oii, parabéns pelo projeto!

Então, eu vi que tem a página https://nalanda-dias.github.io/Calculadora/ do github pages, mas ela não está funcionando.

Só se acessar o arquivo direto com https://nalanda-dias.github.io/Calculadora/Calculadora.html

Se você renomear o `Calculadora.html` para `index.html`, ele vai funcionar direto :)

**Comment by Nalanda-Dias** [comment]
Obrigada pela ajuda, eu havia tentado arrumar isso mais não tinha
conseguido!!

Em sex, 29 de out de 2021 14:10, Luis Felipe Santos do Nascimento <
***@***.***> escreveu:
